### ISSUE TITLE
v1.3.0 Prep

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#381] opened 2017-09-28 15:08 UTC
## Next release: v1.3.0 - Monday October 2nd

_Note: iPhone is currently in v1.2.0 and Android is currently in v.1.1.0. Going to bump version number to 1.3.0 so that they both match_

- Today (September 28) - Plan is to close and merge all open PRs that are safe to merge

- The next few days, we should focus on fixing any bugs and applying UI fixes to anywhere that needs it. Please tag this issue on those PRs. We'll put a hold to merging large features/updates to the app until after Monday.

## Some things that need updating:

- [x] ImageZoom component shows a black screen when image is tapped (iPhone + Android)

   EDIT - Just seems to be the native module not linking properly. Thanks @machour for pointing this out

![image](https://user-images.githubusercontent.com/12476932/30973594-82bc7942-a43b-11e7-9d20-0dd7ec968b0a.png)

- [X]  Font on events screen seems _too_ bold on iPhone (only seeing this issue myself, @machour can't reproduce it which is interesting <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:56.25000000000001% 70.83333333333334%;background-size:4900%" data-codepoints="1f914"></span></span>)

![image](https://user-images.githubusercontent.com/12476932/30973677-b156341e-a43b-11e7-8e84-c8a7968d195f.png)

- [x] Something that I've been thinking, update fonts in app to [Nunito](https://fonts.google.com/specimen/Nunito)

![image](https://user-images.githubusercontent.com/12476932/30974049-a4517f3e-a43c-11e7-971e-dd62d42cc454.png)

Have been working on a React Native app this past week that uses this font and it really looks _crisp_. Will be also be perfect to have both platforms use the same font. Will give this a shot :)

- [X] Change notifications count badge, make number slightly larger/prominent

Instead of splitting these concerns into separate tickets, I'm okay with having PRs for each but just using this ticket ID. Anything that you can see that we most definitely need to include, don't hesitate to comment it here and we'll add it in the list.

# EXCITED TO GET A NEW RELEASE OUT!

![excited](https://media.giphy.com/media/pUs87dXYIIrTy/source.gif)

**Comment by housseindjirdeh** [comment] 2017-09-28 15:17
After our release, we'll spend some significant amount of time improving a number of things in the app:

- Streamlining release flow and CI using Fastlane and Buddybuild or bitrise
- Rearchitecting our state to leverage normalizer (progress began here #350)
- Moving over to GraphQL incrementally (progress began here #347)
- Lay out a more concrete UI guideline flow (similar to how buttons are being mapped here #374)
- Keep adding more features! For me the real big wins are things like Enteprise support as well showing pull request review comments for example. But there's still a ton of amazing things left to add

All the above is for future discussion, but just wanted to put that here in case people where were wondering what's next :)

**Comment by machour** [comment] 2017-09-28 15:22
* Implement a solid and verbose `v3` client implementing all high level api calls (v3.user.getOrgs(), etc.) and use only the high level api in `*.actions.js`. No more direct calls to v3.get() and other low level methods.

**Comment by andrewda** [comment] 2017-09-28 18:07
Super excited for this!!

Side note, can we be sure to use the semver terms for releases (`v1.3.0`) just in case we have to release a patch?

**Comment by housseindjirdeh** [comment] 2017-09-28 18:11
Yep that's a good point, will make sure to use semver from now on 🙌

**Comment by housseindjirdeh** [comment] 2017-09-29 20:07
@lex111 Just noticed two minor things:

- [ ] The 99+ icon doesn't show perfectly for iPhone:

![image](https://user-images.githubusercontent.com/12476932/31033935-fc666524-a52f-11e7-84a6-30483fa51256.png)

- [ ] When Mark all Notifications is tapped, it doesn't refresh the pending and all notifications screens:

![notifications-update-needed](https://user-images.githubusercontent.com/12476932/31033979-1ab55814-a530-11e7-9e24-fa264b31a759.gif)

- [ ] Think we can update the Mark All Notifications Button as `green` maybe to match the merge button?

Please don't feel like you have to get to this right now. Just putting it here so we can address it before our release on Monday :) (more than happy to take care of it myself)

**Comment by lex111** [comment] 2017-09-29 20:12
> When Mark all Notifications is tapped, it doesn't refresh the pending and all notifications screens:

This I fixed in #371, but need to check so.

> The 99+ icon doesn't show perfectly for iPhone:

Ooops, I'll fix it, admit I did not look at iOS :(

By the way, will we change the fonts so that they have the same everywhere?

**Comment by housseindjirdeh** [comment] 2017-09-29 20:23
> This I fixed in #371, but need to check so.

Seems to be what's happening on #371 unfortunately. No worries it isn't anything major breaking. I'll merge it in and we'll triage it in `master`.

> Ooops, I'll fix it, admit I did not look at iOS :(

> By the way, will we change the fonts so that they have the same everywhere?

Yep exactly so that's why I don't want you to stress over it, I'm going to be applying UI updates with the font change anyway

> #371  is not yet merged, so it's better to write it down there :)

Yep was thinking the same thing :)

**Comment by lex111** [comment] 2017-09-29 20:26
@housseindjirdeh Ok, for the weekend I think we'll do it, but the font you can do?

**Comment by housseindjirdeh** [comment] 2017-09-29 20:28
@lex111 Yep I can take care of that :) If not today then tomorrow!

**Comment by machour** [comment] 2017-09-30 14:38
⚠️ we need to merge https://github.com/gitpoint/git-point-site/pull/10 and change the host in `MarkdownWebView` before the release.

**Comment by jouderianjr** [comment] 2017-09-30 15:00
hey everyone, I was talking with @machour on gitter about #327 as he said, some user normally keeps his finger on the screen while scrolls the app. In issue screen, we added the long press event and for these users, this long press event could be very annoying. 

Personally, I have this exact problem when I use facebook app :/

What do you think about to remove it?

**Comment by Antoine38660** [comment] 2017-09-30 18:01
>  Font on events screen seems too bold on iPhone (only seeing this issue myself, @machour can't reproduce it which is interesting 🤔)

I can't reproduce it too 🤔 Descriptions (grey parts) doesn't look bold at all

> Something that I've been thinking, update fonts in app to Nunito

I can try to add Nunito instead of AvenirNext and OpenSans and give you some screenshots !

Excited by this new release 😍 🎉

**Comment by housseindjirdeh** [comment] 2017-09-30 20:01
@machour Noted!

@jouderianjr yep personally very okay with removing the long press entirely :)

@Antoine38660 Interesting i have no idea why it's just me lol 🤔 Would love it if you can help out adding Nunito :) Please let me know as soon as you can how it goes!

**Comment by housseindjirdeh** [comment] 2017-09-30 20:02
🐛 Noticing the `private` box gets squeezed with long repo titles:

**Comment by lex111** [comment] 2017-09-30 20:07
@housseindjirdeh I'll try to fix it.

**Comment by Antoine38660** [comment] 2017-09-30 23:53
Here's the new Nanuto font : 

* **iOS**
<img width=200 alt="simulator screen shot - iphone 6 - 2017-10-01 at 01 06 51" src="https://user-images.githubusercontent.com/9287184/31050235-fde64a02-a644-11e7-95cd-58032c735208.png">  <img width=200 alt="simulator screen shot - iphone 6 - 2017-10-01 at 01 10 43" src="https://user-images.githubusercontent.com/9287184/31050254-7cdee396-a645-11e7-82de-16ed1a2fecaa.png"> <img  width=200 alt="simulator screen shot - iphone 6 - 2017-10-01 at 01 09 07" src="https://user-images.githubusercontent.com/9287184/31050255-7d023468-a645-11e7-91b6-fce9246480c6.png"> <img  width=200 alt="simulator screen shot - iphone 6 - 2017-10-01 at 01 09 03" src="https://user-images.githubusercontent.com/9287184/31050256-7d052c5e-a645-11e7-9e35-879e1a3d7c77.png">

* **Android**
TBC...

**Comment by housseindjirdeh** [comment] 2017-10-01 02:39
@Antoine38660 It looks soooo good, running it on my simulator and its sweet :clap:

**Comment by housseindjirdeh** [comment] 2017-10-01 02:40
:warning: The events screen doesn't immediately update with a language change :thinking: 

![translation-bug](https://user-images.githubusercontent.com/12476932/31051215-490f9020-a630-11e7-8b6c-cbfd20fce976.gif)

**Comment by housseindjirdeh** [comment] 2017-10-01 02:41
:warning: We'll need to fix any remaining translations (shouldn't be too many)

**Comment by lex111** [comment] 2017-10-01 15:27
> :bug: Noticing the private box gets squeezed with long repo titles:

I can not fix it :confused: . I thought to put this Text in another Text component, and then everything is fine, but padding and border do not work.

**Comment by lex111** [comment] 2017-10-01 16:54
@chinesedfan maybe you can help? How did you [put the icon at the end of the title](https://github.com/gitpoint/git-point/pull/387#issuecomment-333318911)? At us now a [problem with that it is incorrectly displayed an notice "Private"](https://github.com/gitpoint/git-point/issues/381#issuecomment-333332578), it too is in the end.

**Comment by housseindjirdeh** [comment] 2017-10-01 17:05
Here's the [gist](https://gist.github.com/housseindjirdeh/6953891ef108f2f284c2cecd2e372f05) I linked to @chinesedfan showing how to flex position something to the right. Unfortunately this is going to be a little trickier since there's already an icon positioned to the far right. We'll have to flex position both the icon and private box as a `column` view within the whole flexed `row`.

I can help with that in a few hours when I'm back on my machine :raised_hands:

**Comment by housseindjirdeh** [comment] 2017-10-01 17:29
![image](https://user-images.githubusercontent.com/12476932/31056991-368ca0fe-a6a9-11e7-882a-ac929dd69e65.png)

`IssueListItem` subtitle looks too bold and title doesn't look bold enough. Should look more like this (in terms of boldness):

![image](https://user-images.githubusercontent.com/12476932/31057052-3681c17e-a6aa-11e7-9f97-d90fb1f47fd2.png)

**Comment by housseindjirdeh** [comment] 2017-10-01 17:45
![image](https://user-images.githubusercontent.com/12476932/31057285-3d5d40aa-a6ae-11e7-8a5d-936533be3f3a.png)

Issue parent comment isn't padded with the border bottom properly. We could add functionality to only _edit_ the parent comment if the user is the current user but if we're in a rush we can leave that to a future release and just add the bottom padding

**Comment by housseindjirdeh** [comment] 2017-10-01 22:55
Editing issue comment doesn't show the comment by default.

![editissue](https://user-images.githubusercontent.com/12476932/31060059-13ae75ae-a6da-11e7-8827-7b9edb2f698a.gif)

Exploring now :mag:

**Comment by machour** [comment] 2017-10-01 22:58
@housseindjirdeh might be related to api changes

**Comment by chinesedfan** [comment] 2017-10-02 04:14
@housseindjirdeh @lex111 Does the private box problem fixed? The screenshot shows wrong height.  I agree that pending it at the end of the repository name is better than the current left-right structure. But it will meet the same space problem as I mentioned in #387.

**Comment by lex111** [comment] 2017-10-02 04:48
@chinesedfan in general, [yes](https://github.com/gitpoint/git-point/pull/409), but she decided that the name of the repository was reduced, i.e. not really a solution to the problem. It's strange that there is no way to place something at the end of Text component, given that it can be multi-line.

**Comment by chinesedfan** [comment] 2017-10-02 06:33
@lex111 You can add View as a child of Text, then it will flow to the end of the text. For example:
```
<Text>
  <Text>aaaaaaaaaaa</Text> // very long
  <View style={{ width: 10, height: 10 }} /> // without size, it will throw an error
</Text>
```
The result is:
```
aaaaaaaaa
aa<View>
```

**Comment by lex111** [comment] 2017-10-02 06:35
> without size, it will throw an error

Now I understand why I had a mistake. And it turns out to dynamically determine the real dimensions through `onLayout`?

**Comment by chinesedfan** [comment] 2017-10-02 06:45
I don't know the inner logic, but network articles say it only works with the size is set. I like this layout except for the following problem:

```
aaaaaaaaa
aa_<View> // we need padding
```
```
aaaaaaaaa  // just one line
_<View>    // but starting with padding is annoy
```

**Comment by lex111** [comment] 2017-10-02 06:46
>  but starting with padding is annoy

And it starts with a new line?

**Comment by chinesedfan** [comment] 2017-10-02 06:56
I mean the text and the view flow in multiple lines. If the length of the text happens to be the length of one line, then after wrapped, the second line will start with the view. But the padding is still there, like the 3rd item in the next screenshot.

<img width="375" alt="2017-10-01 12 16 11" src="https://user-images.githubusercontent.com/1736154/31047460-cb8e0316-a5d0-11e7-99f6-9bba17477d99.png">

By the way, maybe we can chat at Gitter.

**Comment by lex111** [comment] 2017-10-03 21:02
@housseindjirdeh when is the release?

**Comment by housseindjirdeh** [comment] 2017-10-04 03:26
@lex111 Literally put it up for iOS app review:

![image](https://user-images.githubusercontent.com/12476932/31158771-34965aa2-a892-11e7-8f99-a6402a2a2d95.png)

Hopefully by tomorrow it'll be approved and rolled out 🙏

**Comment by housseindjirdeh** [comment] 2017-10-04 03:28
@lex111 Running a production build for a final run through for Android and I'm noticing icon issues 😞 

![image](https://user-images.githubusercontent.com/12476932/31158808-7cf4b92e-a892-11e7-9d97-97742701fa3e.png)

Did you mention running `link` solved the problem?

**Comment by housseindjirdeh** [comment] 2017-10-04 03:46
^ Nvm, running yarn and `link` again fixed things :o

Next release rolled out for Android! 
![image](https://user-images.githubusercontent.com/12476932/31159150-03256e10-a895-11e7-9213-3234442a3c2c.png)

**Closed** 2017-10-04 19:18 UTC
Labels: high priority, release
