### ISSUE TITLE
Can't sign in with android

### ISSUE THREAD

**Issue by mathieutu** [gitpoint/git-point#199] opened 2017-08-05 10:30 UTC
Hi.
Thank you for the android version, I was waiting for it!

Unfortunately, I can't pass the sign in step.
The click on button doesn't do anything.

I'm on Samsung Galaxy s6, android 7, official rom.

If I can help you with some logs, I'll be glad to.

Thanks for your work.  
Matt'

**Comment by introwit** [comment] 2017-08-05 12:27
@mathieutu cross checked on my android and it works. When you click on the sign in button it opens up the browser rather than using the in app web view (an improvement I will suggest in the coming days). So I guess the browser isn't firing up. Do you have the latest chrome installed on your phone? If yes you can clear Chrome's cache, force-stop it and retry after few minutes. Let me know if that works or not :)

**Comment by AndonyNS** [comment] 2017-08-05 14:45
Hi! I was able to sign in from my Android device. I would try also with another browser and make it the default to check if it is a browser thing or from the app. It may help if some else has the issue. I'm on Android 7.1

**Comment by housseindjirdeh** [comment] 2017-08-05 16:56
Thank you so much @AndonyNS @introwit :)

Thank you @mathieutu - we're so happy to have the Android version finally released as well! I can't reproduce the issue as well however- it's the sign in button on the onboarding swiper screens that doesn't seem to do anything correct? Let us know if changing the default browser on your device works, if it doesn't don't worry we'll figure out what's going on. 

Will appreciate it if _any_ other Android users who experience anything remotely similar to let us know as well!

**Comment by mathieutu** [comment] 2017-08-07 12:28
Yes this is this button.
I have [Firefox](https://www.mozilla.org/en-US/firefox/android/) last version.
I'll try to change it and re test (but anyway, I shouldn't do that for a normal use).

**Comment by mathieutu** [comment] 2017-08-07 12:48
Ok, I've found it.

When I remove Firefox from default browser, the signIn redirected me on another git app I had on my device (fasthub), and its internal browser. I wasn't able to press the github "authorize" button (stay deactivated).

I've uninstalled it, and now when I press signIn, I'm going to firefox, and no problem to signIn.
I've re setted Firefox as the default browser, and no problem.

I think that as @introwit said, the in app web view is really needed to avoid theses conflicts..

**Comment by housseindjirdeh** [comment] 2017-08-14 16:06
Thank you @mathieutu, apologies for the struggle needed to solve this problem :(

Going to prioritize that ticket and make sure we have that implemented soon. If no one picks it up sooner, it'll be the next thing I work on.

Will close this ticket as we have that one to reference the problem. Thanks again for logging this mate 🙌

**Closed by housseindjirdeh** 2017-08-14 16:06 UTC
Labels: android, bug
