### ISSUE TITLE
Discussion - Move to Redux Actions + Reselect

### ISSUE THREAD

**Issue by alejandronanez** [gitpoint/git-point#520] opened 2017-10-20 03:06 UTC
Hey all!
I'd like to get your feedback about start migrating our actions/reducers to `redux-actions` and `reselect`. Here's a PR I created a while back to the organizations actions/reducers.
I think this is a good move, we will reduce our boilerplate greatly and will let us organize our application in a **more elegant** and **legible way**.

If we decide that this is a good move, I can update the docs and will create a list similar to what @andrewda did for the unit tests in #518 

https://github.com/gitpoint/git-point/pull/269

Thanks!!!

**Comment by machour** [comment] 2017-10-20 11:12
I don't think it makes sense to change the way we access the store, while the store itself is broken by design. We'll be just changing the paint on a cracked wall.

I've been pulling a lot of thinking into this ( #457 ) and would appreciate to have the chance to continue in this direction, as it would lead us to no boilerplate **at all**, while fixing the store design and enabling us to add new API requests in an easy manner.

**Comment by machour** [comment] 2017-10-20 11:27
@alejandronanez it would completely modify all the store architecture.

Whenever you have 30mn~1hour, I'll be glad to do a 1 on 1 with you to walk you through the changes, I'm sure you'll like what you see ;)

**Comment by alejandronanez** [comment] 2017-10-20 15:26
Oh I'm glad you decided to close that huge PR and split it into small pieces, that will make things easier 👍 !
FWIW I think `redux-actions` can integrate with what you have in mind and the same goes for `reselect`.
* `redux-actions` will reduce the boilerplate when you want to dispatch something and will help us reduce some code from the reducers.
* `reselect` is a better way to query the store.

**Comment by machour** [comment] 2017-10-20 15:31
I'll try `reselect` and see how to ease objects retrieval with it, looks nice!

`redux-actions` on the other hand isn't really needed as reducers are already really simple and all the dispatching is done in a single point for all actions (the proxy).

I'll open the new simplified PR shortly to move forward with this

**Comment by alejandronanez** [comment] 2017-10-20 15:32
Sounds good! Thanks!

**Comment by jglover** [comment] 2017-10-24 15:13
Normalizr and reselect can massively reduce the amount of transformation and prop manipulation, this re-rendering done. But nicer still, Github released v4 of their API with GraphQL support, so you can retrieve a normalised well-shaped response right out of the gate, may be worth looking at: https://developer.github.com/v4/

**Comment by machour** [comment] 2017-10-24 20:28
@jglover we have some on-going discussions/PRs about GraphQL: #141 #455 #347 
The idea for now is to mix both GraphQL & Rest in the future

**Comment by jglover** [comment] 2017-10-25 03:51
That's great, in which case I definitely support reselect and normalizr for REST based work. Much less transformation then, schemas are also loosely akin to interfaces in Typescript and I think that kind of transparency into the request/response models is a great help.

**Comment by machour** [comment] 2018-03-31 14:38
Closing this issue as we started a massive refactoring of our Redux store.
More details in #761

**Closed by machour** 2018-03-31 14:38 UTC
Labels: discussion, question, refactor, tech debt
