### ISSUE TITLE
Stuck on authorization screen

### ISSUE THREAD

**Issue by HaLeiVi** [gitpoint/git-point#680] opened 2017-12-27 00:33 UTC
I'm using a Samsung Galaxy S3 running Android 4.4.2. I am able to enter login info. Then I'm taken to the authorizing screen, but it stays there. The authorize button and even 'cancel' is unresponsive.

**Comment by housseindjirdeh** [comment] 2017-12-27 01:34
Thanks for logging this @HaLeiVi.

Someone just recently showed me this problem on their Android device as well, will look into it soon and find out what's going on.

**Comment by machour** [comment] 2017-12-27 13:22
Javascript wasn't enabled on this Webview, and the GitHub authorization screen [seems to need it](https://stackoverflow.com/questions/44425233/why-is-the-github-authorization-button-in-the-oauth-flow-grayed-out). Opened #681 to fix it.

However, weirdly enough the auth process always worked on my OnePlus 3T device, without enabling JS. 🤔

**Comment by housseindjirdeh** [comment] 2018-01-03 00:35
Thanks a million @machour 

@HaLeiVi if you don't mind, I'll generate an APK for you to test on your device if that's okay? You'll get the app working for you sooner that way and we can confirm that this indeed fixes it (especially since I can't reproduce this on any android device)

**Comment by HaLeiVi** [comment] 2018-01-03 14:41
Sounds great!

**Comment by housseindjirdeh** [comment] 2018-01-18 15:10
So sorry for the delay @HaLeiVi, but here's the apk with the fix: https://github.com/gitpoint/git-point/releases/tag/hotfix

Give it a shot whenever and please let me know if all is well! We should have a release with this fix in about a week.

**Comment by linrz** [comment] 2018-01-30 10:45
![screenshot_2018-01-30-18-42-41-989_com gitpoint](https://user-images.githubusercontent.com/33575974/35562149-1b9188d6-0578-11e8-8d36-eae5ec420fef.png)
I download the latest apk.It seems still can not work.

**Comment by machour** [comment] 2018-01-30 10:49
@linrz hey, did you download the APK from the provided link to debug this issue?
    https://github.com/gitpoint/git-point/releases/tag/hotfix

**Comment by linrz** [comment] 2018-01-30 14:24
@machour Yes, I download this pre-release APK  which released 12days ago. My android's version is 6.0.1. It seems this webview use IE caused it.
![wechatimg116](https://user-images.githubusercontent.com/33575974/35571164-4a490f16-060c-11e8-9b6f-4d7a8abec435.jpeg)

**Comment by HaLeiVi** [comment] 2018-01-30 14:43
I got the same results. I was able to enter password, and verify it. But
couldn't go past that screen.

**Comment by machour** [comment] 2018-01-30 15:08
Ok Houston, we definitely have a problem 😄 
I think we have to get rid of the webview and use something like [react-native-oauth]( https://github.com/fullstackreact/react-native-oauth) to handle signins

**Comment by machour** [comment] 2018-01-30 17:54
Got in touch with GitHub to confirm:

> Thanks for reaching out. The button is always initially disabled, but it is re-enabled automatically by JavaScript running in that page. (This behavior is there to prevent certain types of attacks.) You'll see this if you reload the page in your browser and look closely at the button --you'll see it's disabled at first and then is enabled after a second or so.

> I'm guessing that running the page outside of a regular browser might be affected by some configurations, and might need tweaking to get the JavaScript to run properly. Can't say what those might be since it's not something we provide support for. Still, I hope this helps.
```

**Comment by HaLeiVi** [comment] 2018-01-30 17:59
IIRC, you have to explicitly allow JavaScript for the webview.

**Comment by machour** [comment] 2018-01-30 18:03
@HaLeiVi this was the case in the hotfix you tested: https://github.com/gitpoint/git-point/blob/hotfix/src/auth/screens/login.screen.js#L363

**Comment by housseindjirdeh** [comment] 2018-01-31 21:59
Are we still seeing the issue with `javaScriptEnabled` flag, or did I happen to boot up the APK before you updated it @machour?

**Comment by machour** [comment] 2018-03-22 15:47
@HaLeiVi could you remove the app and install https://idk.tn/gitpoint-test.apk ?

After clicking "Sign in" you should see a really ugly "Can't sign in?" button that will open the GitHub oAuth URL in your browser. Tell me if that works for you 🙏

**Comment by machour** [comment] 2018-04-03 09:47
Fixed in #749

**Closed by machour** 2018-04-03 09:47 UTC
Labels: :bug:  bug, android, has pr

**Comment by yusuf-gunaydin** [comment] 2018-05-17 18:32
I see the same issue on freshly installed iOS version. I have tried with iPhone 6s iOS 10.2.1 and iPad Mini iOS 9.3.5.
