### ISSUE TITLE
Back-Button is buggy

### ISSUE THREAD

**Issue by FlorianTaut** [gitpoint/git-point#70] opened 2017-07-15 10:39 UTC
Hey,

The back button in issues is not working correctly.

For example:
In the gitpoint app open issue #55. There is a reference to #2 click on it. Than go back.
#55 should be displayed and "#55" is Standing on top of the page but #2 is displayed.

Hopefully everbody understands what i mean....

Thank you

**Comment by FlorianTaut** [comment] 2017-07-15 10:42
Sorry duplicate to #3 overseen that one :laughing:

**Comment by alejandronanez** [comment] 2017-07-15 15:49
Thanks for reporting this @FlorianTaut, I'm closing this since it seems like a dupe of #3 
Let me know if I'm wrong so I can re open it.

**Closed by alejandronanez** 2017-07-15 15:49 UTC
