### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zhouxxiaolong** [gitpoint/git-point#94] opened 2017-07-17 05:43 UTC
Unable to resolve module `config` from `/Users/github_clone/git-point-master/App.js`: Module does not exist in the module map.
How to steal?

**Comment by junedomingo** [comment] 2017-07-17 05:47
Hi @zhouxxiaolong , try to clear the packager cache 
`sudo npm start --reset-cache`

**Comment by patw0929** [comment] 2017-07-17 05:59
If you use yarn, run `yarn start -- --reset-cache`.

duplicate of #52.

**Comment by zhouxxiaolong** [comment] 2017-07-17 07:28
Thanks,it’s working.

**Comment by zhouxxiaolong** [comment] 2017-07-17 07:29
Thanks,it’s working.

**Closed** 2017-07-17 07:39 UTC
