### ISSUE TITLE
Crash when commenting on issue

### ISSUE THREAD

**Issue by AndonyNS** [gitpoint/git-point#201] opened 2017-08-05 16:59 UTC
I was commenting on an issue and the app crashed. I then came back and posted the message again and it worked. I don't know if you have something like crashlytics with the app but I couldn't reproduce it to make it clearer

**Comment by andrewda** [comment] 2017-08-05 17:02
Yep, I noticed this too. Not sure what the problem is.

**Comment by housseindjirdeh** [comment] 2017-08-05 17:07
Ah thanks folks. Would you happen to know which `issue` this error happened - I hope I can reproduce this locally to figure out what's going on (I have a strong feeling [this is culprit](https://github.com/gitpoint/git-point/pull/160#discussion_r129202004)).

**Comment by pfinkbeiner** [comment] 2017-08-21 05:01
Same here… At least on my iPhone I can reproduce it.
At the beginning everything works like expected. But when I try to open an issue in a repository which is private, I don't get any feedback after submitting and the app freezes. 

The strange part is: after this freeze happend I'm not able to open any other issues on public projects. The app quits immediately.

**Comment by housseindjirdeh** [comment] 2017-09-08 09:47
Hmmm @pfinkbeiner that is kinda concerning. we'll dive in and I'll try to reproduce this issue locally with a private repo as well. Will keep you folks posted

**Comment by chinesedfan** [comment] 2017-09-16 05:59
@pfinkbeiner @housseindjirdeh  I guess it is related to #320. The key point is visiting some empty issues.

@AndonyNS @andrewda You mentioned "commenting", which means the issue screen is opened correctly. Then it will be another problem.

**Comment by FlorianTaut** [comment] 2017-10-11 09:22
@chinesedfan i think its not fixed with #320 unfortunately, i have crashes when posting a comment some times. I believe it only crashes when tagging someone with @. 

But im not sure this causes the problem to a 100%

**Comment by SirWindfield** [comment] 2017-12-05 02:50
It is still happening on my android phone. It's quite annoying since I use GitHub apps mainly to communicate for issues/pr.

It happened on every comment I posted within this [issue](https://github.com/KeitIG/museeks/issues/369), even the ones without mentions. I send the crash log using the `Send feedvack` feature from android itself. The email has `trash` within its name, in case you already received it.

It even happened on the last comment from me. And I made sure to not use @mentions.

**Comment by andrewda** [comment] 2017-12-05 02:52
Yes, this still needs to be fixed and should be done as soon as possible.

**Comment by SirWindfield** [comment] 2017-12-05 02:53
Anything I can do to help you identify the probem? Maybe run a debug version of the app somehow?

**Comment by machour** [comment] 2017-12-06 18:52
@SirWindfield can you tell us the exact comment that you were posting? There might be something in the text that is not well handled.

You can run a debug version by cloning this repo & compiling the app on your phone. That would be really helpful! 
The [setup](https://github.com/gitpoint/git-point/blob/master/CONTRIBUTING.md#setup) section of our contributing guide should get you started, and we will be available on [gitter](https://gitter.im/git-point/Lobby) if you need some support with that.

**Comment by SirWindfield** [comment] 2017-12-06 20:02
It crashed on every single comment that I posted over there. Going to clone and install it on my phone, give me a sec.

**Comment by machour** [comment] 2017-12-09 11:24
I'm able to reproduce this on master, with the following flow:

1. Start the app
1. Go to notifications and pick an issue
1. Comment it

Crash message:
<img width="363" alt="screen shot 2017-12-09 at 12 22 09 pm" src="https://user-images.githubusercontent.com/304450/33795151-d061b314-dcdb-11e7-8fe2-95c1d5088deb.png">

**Comment by SirWindfield** [comment] 2017-12-10 02:42
After some fiddeling, I am getting exactly the same error message.

**Comment by chinesedfan** [comment] 2017-12-10 08:05
@machour @SirWindfield I hope it has been fixed in #658. Check it!

**Comment by machour** [comment] 2017-12-10 10:08
@chinesedfan working for me on Android and iOS, a big thank you mate!
@SirWindfield if you want to test this PR, do the following:
```shell
cd git-point
wget https://patch-diff.githubusercontent.com/raw/gitpoint/git-point/pull/658.diff
patch -p1 < 658.diff
```
then compile the app like you did to reproduce the error.

**Comment by SirWindfield** [comment] 2017-12-11 05:03
Nice, patch is working :smile:

**Closed** 2017-12-11 09:20 UTC
Labels: bug, crash, has pr, high priority
