### ISSUE TITLE
Fix status bar

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#4] opened 2017-07-10 16:00 UTC
Screens that use a profile component (repository screen/user profile screen) should have white status bar text. Currently, the text is dark.

<p align="center">
<img src = "https://user-images.githubusercontent.com/12476932/28027216-510e0762-6566-11e7-88b5-642e715008c4.png" width=250>
</p>

I've already exposed a `barColor` prop to modify this attribute in the [ViewContainer component](https://github.com/housseindjirdeh/git-point/blob/master/src/components/view-container.component.js#L6) which is the wrapper for all screens in the application. However simply changing the value doesn't correctly change the status bar colour as it should, and this probably has to do with how we have nested stack navigations within tabs so it's most likely being overwritten.

**Comment by ShaunLloyd** [comment] 2017-07-12 12:26
@housseindjirdeh I can take a peek at this this afternoon!

**Comment by housseindjirdeh** [comment] 2017-07-12 17:25
Nothing but love for you <3

**Comment by lex111** [comment] 2017-07-19 17:55
@housseindjirdeh on Android, a simple change works. 

> `barStyle={barColor === 'light' ? 'light-content' : 'dark-content'}`

But I do not understand why you need a dark status bar, can by default make it light?

**Comment by andrewda** [comment] 2017-07-19 18:06
@lex111 On almost every screen a dark status bar should be used because a light one would be impossible to see. However, on profiles, orgs and repos, a light one should be used.

**Comment by lex111** [comment] 2017-07-19 18:15
@andrewda mmm, yeah, thanks, I did not understand at first. But however, a simple property change seems to work.

**Comment by housseindjirdeh** [comment] 2017-07-27 17:17
Looping @darecki to the conversation as he similarly tried to simply fix the issue by changing the status bars on the top screens of the stack (see #176)

**Comment by darecki** [comment] 2017-07-27 17:33
I noticed that when the Tab Bar is initiated it loads and renders all its' tab views one by one. The final result is the status bar color is the one defined in AuthProfile, as it is the last screen loaded. It seems that rendering a StatusBar component overrides any previously StatusBar rendered. You can even do things like:
```
<View>
<StatusBar barStyle="light-content" />
<StatusBar barStyle="light-content" />
<StatusBar barStyle="dark-content" />
</View>
```
which will render a view with only one status bar styled as "dark-content" (the last one). Maybe this things are obvious, but it was quite surprising to me, so I'm pointing that out.

Now, my idea of resolving the issue is to re-render the corresponding screen when you change a tab . That would render only the relevant StatusBar. Unfortunately, I have no idea how to force such re-rendering. Can you help me here?

**Comment by Krizzu** [comment] 2017-10-05 20:13
Hey,
What about setting status bar color imperatively [using setBarStyle](https://facebook.github.io/react-native/docs/statusbar.html#setbarstyle)? 
You'd not need to pass props anymore, as this setting will be just in one place.

Also, exposing a option in app settings to change status bar color would be great :)

**Comment by machour** [comment] 2017-11-05 13:43
Assigned @jouderianjr as he's working on it, using `setBarStyle` as mentioned by @Krizzu

**Closed** 2017-12-01 14:58 UTC
Labels: bug, has pr

**Comment by lex111** [comment] 2017-12-01 15:10
:tada:
