### ISSUE TITLE
App crashes on PR comment

### ISSUE THREAD

**Issue by tautf** [gitpoint/git-point#450] opened 2017-10-08 08:05 UTC
Hey,

I tried to comment at #445

I wanted to write the following:
Hey, i can review this, my native language is German @lex11 @houssaindjirdeh

Sorry I don’t know you exact names atm😂

But when I submitted it the app crashed. 

When i only added @lex11 i was able to submit the comment.

**Comment by machour** [comment] 2017-10-09 18:18
@FlorianTaut was that on android or ios?

**Comment by FlorianTaut** [comment] 2017-10-09 18:40
@machour it was iOS 11.0.2 on a real device. I only had it once yet.

**Comment by tautf** [comment] 2017-10-18 05:58
Update on this, i have crashes at nearly every issue & pr comment.
OS: iOS 11.0.2 iPhone 7
GitPoint: of course latest 😄

**Comment by andrewda** [comment] 2017-10-18 06:25
Me too @tautf

**Comment by machour** [comment] 2017-10-18 08:55
Hopefully this will be fixed in 1.3.1 🤞 
I suspect #429 which was also affecting iOS in some cases

**Comment by vidhill** [comment] 2017-10-27 13:44
Me too, try to leave a comment on an issue, app crashes, iOS real device

**Comment by machour** [comment] 2017-12-06 18:53
I think this is a duplicate of #201

**Comment by machour** [comment] 2017-12-06 19:01
Closing this issue as the PR for it have been merged.

**Closed by machour** 2017-12-06 19:01 UTC
Labels: crash, has pr, ios
