### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by FlonTaut** [gitpoint/git-point#807] opened 2018-06-07 13:53 UTC
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.4.1      |
| Devices tested?  | iPhone 7 |

---

## What Currently Happens?
![image-1](https://user-images.githubusercontent.com/18403881/41103933-9ba7fce2-6a6a-11e8-8940-f456f16991bf.jpg)

## What Do You Expect To Happen?
Strings should be translated to german.
But as discussed in #806 they aren't extracted by the exiting script.

So we need the export script to catch these strings and then translate them

If someone could give me a short hint how the export script works and which steps need to be done, i would like to take a try on this one :+1:

**Comment by chinesedfan** [comment] 2018-06-07 14:04
@FlonTaut `script/extract-i18n.js`, which was introduced by #777, is used to extract the new style `t` into several locale files. But it can not discover any missing strings.

I think you can,
- apply `t` with those missing words, i.e. in `src/components/issue-event-list-item.component.js`.
- then run `npm run i18n:extract` to update locale files.
- try to translate new founds words or just leave them to later translators

**Comment by FlonTaut** [comment] 2018-06-07 15:45
@chinesedfan thank you very much you can assign this issue to, i will take a look today or latest tomorrow! thank you!

**Comment by machour** [comment] 2018-06-09 09:38
Hi guys. This is a duplicate of #795. I've already worked on it, I just need some time to finish it.  
Closing this issue for now.

**Closed by machour** 2018-06-09 09:38 UTC
Labels: help wanted

**Comment by FlonTaut** [comment] 2018-09-10 07:54
@machour How are you doing with the work? Do you need any help to finish this?
