### ISSUE TITLE
repository list not showing with > 6 repos

### ISSUE THREAD

**Issue by RogerAbyss** [gitpoint/git-point#151] opened 2017-07-23 09:58 UTC
I find that there is nothing when repositories > 6.
I suggest we give a default sort by stars.Do you think so?
![9b87e44b-390f-49d8-8e14-b10a37da1847](https://user-images.githubusercontent.com/8122587/28498440-1a06ff16-6fd0-11e7-97df-9c67960215c7.png)

**Comment by lex111** [comment] 2017-07-23 14:58
> I suggest we give a default sort by stars.Do you think so?

Can make a drop-down list with sorting alphabetically, the number of stars, the last update, etc. Similarly as done in GitHub?
![image](https://user-images.githubusercontent.com/4408379/28500406-6f5e5ee6-6fd0-11e7-84e3-d0b08382df46.png)

**Comment by housseindjirdeh** [comment] 2017-07-24 01:02
@RogerAbyss cheers thanks for this, are you seeing nothing _at all_ when repositories are > 6?

@lex111 I don't think GitHub allows for that type of sorting for user repositories but I do agree that would be awesome to have in global search. However that doesn't sound extremely trivial to do. What would probably be easier would be to implement a picker that would show when `Sort: Best Match` is clicked to show the other options for example. This seems like it could do the job: https://github.com/beefe/react-native-picker

What do you think? If that's something we agree on I'll like to have that as a separate issue and this can be solely for discussing the bug @RogerAbyss is experiencing in the repositories screen

**Comment by lex111** [comment] 2017-07-24 04:39
@housseindjirdeh agree, let's create a separate issue. And in this issue we will fix bug.

Perhaps this is due to the bug that the repositories of the organization were not displayed.  @RogerAbyss we need more details on how to reproduce this.

P.S. I only one seems strange that in the screenshot the search icon is centered?

**Comment by RogerAbyss** [comment] 2017-07-24 13:05
@lex111 yes.It reproduce easy In my simulator.Just choose a person,respositories has more than a numbers, and it seems like is 6.
<img width="375" alt="192fc398-9990-4e60-a26a-5e4d18744fdd" src="https://user-images.githubusercontent.com/8122587/28524263-527af9f0-70b2-11e7-9a0e-54d5af279f7b.png">

this is @housseindjirdeh `s repositories page, he has 43.
<img width="375" alt="31596254-c2ba-4bb4-a1de-e1b9f92c0456" src="https://user-images.githubusercontent.com/8122587/28524512-625ab8be-70b3-11e7-9583-19f801e80b29.png">

here is mine, i have 5.
![b6eb3c09-9e38-45fe-a6ed-2026921af9fe](https://user-images.githubusercontent.com/8122587/28524525-75d735fc-70b3-11e7-9804-c1134c574738.png)

simulator iphone 6 IOS 10.3
![bf595cce-e99c-4484-b844-1ebde3404679](https://user-images.githubusercontent.com/8122587/28524335-9bfdb568-70b2-11e7-915c-07d37d6adeb8.png)
I see that every has some repositories in persional-page like this:
![e9bc2b78-7461-4d5d-bb72-1882587c91d2](https://user-images.githubusercontent.com/8122587/28524377-c8b339c0-70b2-11e7-9550-1495d9847ef2.png)
maybe we can use this api~
@housseindjirdeh @lex111 , do you think so?

**Comment by lex111** [comment] 2017-07-24 17:30
@RogerAbyss Hmm, I have correctly displayed repositories in people who have more than 6 repositories. Although I'm looking at the Android emulator, maybe this is a problem for iOS, but unfortunately I can not check it :(

Let's wait for others members who can check it on iOS.

**Comment by andrewda** [comment] 2017-07-24 17:31
I can take a peek at this in a bit.

**Comment by housseindjirdeh** [comment] 2017-07-25 14:54
Thanks - this is definitely a really interesting bug. This might sound weird but can you try scrolling the repository list and seeing it pops up? I've experienced `FlatLists` not rendering until the user tries scrolling before and I've had to use [`removeclippedsubviews`](https://facebook.github.io/react-native/docs/flatlist.html#removeclippedsubviews) to render it immediately (don't think this is the same thing but just wondering in case it is)

Thanks a million @andrewda, let us know if you notice anything weird

**Comment by andrewda** [comment] 2017-07-25 22:33
I can't replicate this issue on iOS 10.0 or iOS 11.0 beta 2.

**Comment by housseindjirdeh** [comment] 2017-07-26 00:14
Neither can I :thinking: 

Closing this for the moment, but please let's keep this discussion open @RogerAbyss - I really want to know if you're still seeing this issue

**Closed by housseindjirdeh** 2017-07-26 00:14 UTC
Labels: bug, help wanted
