### ISSUE TITLE
Tabs in the tab bar do not show up on iPad

### ISSUE THREAD

**Issue by Shock9616** [gitpoint/git-point#860] opened 2018-12-28 15:33 UTC
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.6.0      |
| Devices tested?  | iPad 6 |

---

## What Currently Happens?

When I open the app, the tab bar shows up in the bottom of the screen but none of the tabs show up in the tab bar. I can still click them but I can’t see which one I’m clicking

## What Do You Expect To Happen?

I expected to be able to see the tab icons that I am trying to click

## My Reproduction Steps

1. Open GitPoint on an iPad 6. (I’m guessing that it is a problem with the iPad version of the app so it would probably happen on other iPad models too.)
2. Look at the tab bar. There are no tab icons there

![0e8b549b-b51f-406a-afba-066c9e2142c7](https://user-images.githubusercontent.com/28808006/50520238-0d789080-0a74-11e9-9ce9-8865d3af7a88.jpeg)

**Comment by chinesedfan** [comment] 2018-12-28 15:50
Duplicate of #850. Thanks for your detailed description all the same. We really didn't test much in iPad. Let's keep tracking there.

**Closed by chinesedfan** 2018-12-28 15:50 UTC
